# 4. NumPy를 사용한 수치계산

#### Point
* Numpy 핵심기능 복습  
* 연산 속도 중점으로  


### 4.1 데이터배열 
* 배열 (행과 열을 가짐) -> 과학, 금융 분야에서는 더 빠른 연산이 가능한 특별한 자료구조가 필요 
* 배열 대신 쓸 수 있는 두 가지 방법 

#### 4.1.1 파이썬 리스트를 사용한 배열

In [1]:
# Python List
v = [0.5, 0.75, 1.0, 1.5, 2.0] 
print(v)

# 중첩된 구조
m = [v,v,v]
display(m)

# 인덱싱 
print(m[1])
print(m[1][0])

[0.5, 0.75, 1.0, 1.5, 2.0]


[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

[0.5, 0.75, 1.0, 1.5, 2.0]
0.5


In [2]:
# 복잡한 중첩 구조 
v1 = [0.5, 1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
print(c)
print(c[1][1][0])

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]
1


In [3]:
# 객체 조합 방식 : 참조 포인터 Mutable : Shallow copy (주소 참조값이 복사됨)
v = [0.5,0.75,1.0,1.5,2.0] 
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [4]:
# 변수에 저장된 것은 객체의 요소들이 저장된 참조 -> 실제값 변경가능
v[0] = 'Python'
display(m)
print('변수 m의 id',id(m[0]))
print('변수 v의 id',id(v))

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

변수 m의 id 1475933720832
변수 v의 id 1475933720832


In [5]:
# deepcopy() 가 들어가야함 객체를 공유하지 않음 
from copy import deepcopy
print('변수 m의 id',id(m[0]))
print('변수 v의 id',id(v))
m = 3 * [deepcopy(v),]

display(m)
print('변수 m의 id',id(m[0]))
print('변수 v의 id',id(v))

v[0]= 'Python'
display(m)
print('변수 m의 id',id(m[0]))
print('변수 v의 id',id(v))

변수 m의 id 1475933720832
변수 v의 id 1475933720832


[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

변수 m의 id 1475934028352
변수 v의 id 1475933720832


[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

변수 m의 id 1475934028352
변수 v의 id 1475933720832


#### 4.1.2 파이썬 array 클래스

In [6]:
v = [0.5,0.75,1.0,1.5,2.0] 
import array 
a = array.array('f',v) # f= float
print(a)

a.append(0.5)
print(a)

a.extend([5.0, 6.75])
print(a)

print(2*a) # 스칼라 곱이 아닌 반복값이 나와버림

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])
array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])
array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])
array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])


In [7]:
a.append('string') # 필요시 to_list 로 다시변환

TypeError: must be real number, not str

In [8]:
# array class 의 장점 : 저장 및 읽기 기능 
f = open('array.apy','wb') # 파일을연다 
a.tofile(f) # 배열데이터를 파일에 쓴다.
f.close

<function BufferedWriter.close>

In [9]:
with open('array.apy','wb') as f:
    a.tofile(f)

In [10]:
!ls -n arr*

'ls'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [11]:
# 데이터를 디스크에서 읽을 때 자료형 중요?
b = array.array('f')
with open('array.apy','rb') as f:
    b.fromfile(f,5) # b객체 원소를 5번 읽는다
print(b)

b = array.array('d') # 더블 자료형 

with open('array.apy','rb') as f:
    b.fromfile(f,2)

print(b)

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])
array('d', [0.0004882813645963324, 0.12500002956949174])


### 4.2 정규 Numpy 배열

* 리스트는 좀 더 일반적이고 광범위한 목적으로 사용됨  
* 여러가지 단점이 있기에 배열을 잘다루기 위한 특화된 클라쓰 NUMPY!

#### 4.2.1 Basic

In [12]:
import numpy as np 

#배열 생성 
a = np.array([0,0.5,1.0,1.5,2.0])
display(a)

print(type(a))

array([0. , 0.5, 1. , 1.5, 2. ])

<class 'numpy.ndarray'>


In [13]:
a = np.array(['a','b','c'])
display(a)

a = np.arange(2,20,2)
display(a)

a = np.arange(8, dtype=np.float64)
display(a)

display(a[5:])

array(['a', 'b', 'c'], dtype='<U1')

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0., 1., 2., 3., 4., 5., 6., 7.])

array([5., 6., 7.])

In [17]:
# Numpy 의 큰 특징 : 다양한 내장 메서드가 있다.
print(a.sum()) #합
print(a.std()) #표준편차
print(a.cumsum()) #누적합

28.0
2.29128784747792
[ 0.  1.  3.  6. 10. 15. 21. 28.]


In [18]:
# 또다른 특징 ndarray 객체에 대해 벡터화된 수학 연산 가능
l = [0.,0.5,1.5,3.,5.]
print(2*l) # 리스트의 스칼라 곱 = 반복 출력
print(2*a) # ndarray 의 스칼라 곱 = 스칼라곱 
print(a**2)
print(2**a)
print(a**a)

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]
[ 0.  2.  4.  6.  8. 10. 12. 14.]
[ 0.  1.  4.  9. 16. 25. 36. 49.]
[  1.   2.   4.   8.  16.  32.  64. 128.]
[1.00000e+00 1.00000e+00 4.00000e+00 2.70000e+01 2.56000e+02 3.12500e+03
 4.66560e+04 8.23543e+05]


In [19]:
# 유니버셜 함수 -> ndarray 객체에 똑같이 적용 가능
print(np.exp(a))
print(np.sqrt(a))
print(np.sqrt(2.5))
import math 
print(math.sqrt(2.5)) # math ndarray에 바로 적용 불가 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131]
1.5811388300841898
1.5811388300841898


In [20]:
# np.sqrt 는 math.sqrt 보다 속도가 현저히 낮음 
%timeit np.sqrt(2.5)
%timeit math.sqrt(2.5)

1.52 µs ± 51.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
304 ns ± 72.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 4.2.2 다차원


* 1차원을 다차원으로 간단하게 확장  

In [21]:
b = np.array([a,a * 2])
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [22]:
b[0]

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [23]:
b[0,2]

2.0

In [24]:
b[:,1]

array([1., 2.])

In [25]:
b.sum()

84.0

In [26]:
b.sum(axis=0)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [27]:
b.sum(axis=1)

array([28., 56.])

In [30]:
# array 는 모든 원소 값을 이미 알고 있어야함 
# numpy.ndarry 객체 만들고 코드 실행하면서 원소 값 지정 
c = np.zeros((2,3),dtype='i',order='C') #order = 메모리 저장 순서 방식 
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [33]:
c = np.ones((2,3,4),dtype='i',order='c')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [37]:
#_like 어떤 특정 배열과 같은 shape 를 만들겠다.
d = np.zeros_like(c, dtype='f',order='C') 
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [38]:
d =np.ones_like(c, dtype='f', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [40]:
# 아무값이나 들어있는 배열 (값은 메모리 상태에 의존)
e = np.empty((2,3,2)) 
e

array([[[0.0078125, 0.0078125],
        [0.0078125, 0.0078125],
        [0.0078125, 0.0078125]],

       [[0.0078125, 0.0078125],
        [0.0078125, 0.0078125],
        [0.0078125, 0.0078125]]])

In [42]:
f = np.empty_like(c)
f

array([[[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]],

       [[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]]], dtype=int32)

In [45]:
# 대각성분 1인 정방행렬 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
# start, end, count
g = np.linspace(5,15,12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

#### 4.2.3 메타정보

In [48]:
# 원소의 개수
g.size

12

In [49]:
# 원소 하나의 사용된 바이트수
g.itemsize

8

In [50]:
# 차원의 수 
g.ndim

1

In [51]:
# ndarray 객체 형상 
g.shape

(12,)

In [53]:
#type 
d.dtype

dtype('float32')

In [54]:
# 사용된 메모리 총량 
g.nbytes

96

#### 4.2.4 형태 변환과 크기 변환 

* 형태를 바꾸는 것 -> view만 바꾼다  
* 크기를 바꾸는 것 -> 새로운 객체를 생성한다 

In [57]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
print(g.shape)
print(np.shape(g))

(15,)
(15,)


In [61]:
g.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
h = g.reshape(5,3)
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
display(h.T)
display(h.transpose())

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [69]:
# 크기 변환 (2차원 다운사이징) 
display(np.resize(g, (3,1)))
display(np.resize(g,(1,5)))
display(np.resize(g,(2,5)))

array([[0],
       [1],
       [2]])

array([[0, 1, 2, 3, 4]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
# 크기변환 (2차원 업사이징)
n = np.resize(g,(5,4))
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [75]:
#stack 
display(np.hstack((h, 2*h)))
display(np.vstack((h,0.5*h)))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [76]:
# ndarray 객체를 1차원 객체로 펼침 
h.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
display(h.flatten(order='C'))
display(h.flatten(order='F'))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [78]:
# 불리언 배열 
h>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
# 연산을 하면 데이터가 펼쳐진다 
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [81]:
# np.where() 조건 T,F 에 따라 연산 동작 정의 
np.where(h>7,1,0) # 조건, True, False

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [82]:
np.where(h <=7, h*2, h/2)

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

#### 4.2.6 속도비교 

In [86]:
# 5000*5000 행렬/배열을 표준정규분포 난수를 사용하여 생성 
# 순수 python 사용 
import random
I = 5000
%time mat = [[random.gauss(0,1) for i in range(I)]for i in range(I)]

CPU times: total: 35.6 s
Wall time: 36.9 s


In [89]:
mat[0][:5]

[0.5314423123764733,
 -0.49449504890994433,
 -0.32584010084025916,
 0.5453104578517778,
 0.11891819923463007]

In [84]:
# 리스트 조건제시법 내에서 합을 계싼하고 다시 그합을 계싼
%time sum([sum(l) for i in mat])

CPU times: total: 0 ns
Wall time: 2.99 ms


50000.0

In [87]:
# 모든 리스트 원소가 사용한 메모리의 합 
import sys
sum([sys.getsizeof(l) for l in mat])

209400000

In [94]:
# numpy 사용 (10배이상 빠름)
%time mat = np.random.standard_normal((I,I))

CPU times: total: 1.06 s
Wall time: 1.07 s


In [91]:
%time mat.sum()

CPU times: total: 46.9 ms
Wall time: 57 ms


-3073.9615219964107

In [92]:
mat.nbytes

200000000

In [93]:
sys.getsizeof(mat)

200000128

### 4.3 구조화 Numpy 배열

* ndarray 단일 자료형 숫자 배열 연산에 특화 되어 있음  
* 다양한 배열 기반 알고리즘이나 응용분야에서 사용하기 힘들 수 있다.
* 각 열마다 다른 자료형을 사용할 수 있는 structure array와 recarry 레코드 객체 지원 

In [96]:
# 복합 dtype의 생성 
dt = np.dtype([('Name', 'S10'),('Age','i4'),('Height','<f4'),('Children/Pets','<i4',2)])
dt


dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [102]:
# 동일한 결과를 만드는 다른 문법 
# version 문제. 추후 변경
dt = np.dtype({'names':['Name','Age','Height','Children/pets'],
               'formats':'0 int float int,int'.split()})

TypeError: data type '' not understood

In [103]:
s = np.array([('smith',45,1.83,(0,1)),
              ('jones',53,1.72,(2,2))],dtype=dt)

In [104]:
s

array([(b'smith', 45, 1.83, [0, 1]), (b'jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [105]:
type(s)

numpy.ndarray

In [109]:
print(type(s[0][0]))
print(type(s[0][1]))
print(type(s[0][2]))

<class 'numpy.bytes_'>
<class 'numpy.int32'>
<class 'numpy.float32'>


In [115]:
#SQL DB table 생성과 유사 -> 딕셔너리 객체 처럼 슬 수 있음 
#근데 b가 붇는건 뭐지?
print(s['Name'])
print(s['Height'].mean())

[b'smith' b'jones']
1.7750001


### 4.4 코드 벡터화 

* 코드 벡터화 -> 코드를 간결하게, 실행 속도를 빠르게 
* 객체에 연산, 함수 적용시 각 원소의 반복적용이 아닌 객체 전체에 한번만 적용  
* py-> map(),filter()  numpy -> 좀더 깊은 부분 까지 벡터화 가능 

#### 4.4.1 기본적인 벡터화 

In [118]:
np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5 
display(s)
display(r)
display(s+r) #원소별 벡터화 덧셈 (루프 없음) 

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [119]:
# Numpy 의 Broad Casting ( 두 개의 서로 다른 형상을 가진 객체를 조합)
display(r+3)
display(2*r)
display(2*r+3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [122]:
print(r.shape)
s = np.arange(0,12,4)
display(s)
display(r+s)

(4, 3)


array([0, 4, 8])

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [123]:
s = np.arange(0,12,3)
r+s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [124]:
r.T + s

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [125]:

r+s.reshape(-1,1)

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [127]:
# 만든 함수로 사용
def f(x):
    return 3 * x + 5 

In [128]:
f(0.5)

6.5

In [129]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

* numpy.ndarray 객체에 대한 반복문이 대부분 C로 쓰여져 있어 성능이 최적화된 코드를 사용 
* 이것이 Numpy나 배열을 사용하는 경우 성능 향상이 가능한 이유!

#### 4.4.2 메모리 레이아웃 

* 메모리 레이아웃에 대한 인수를 추가 설정 가능  
* 이 인수는 각 배열의 원소가 메모리상에 저장되는 방식임 
* 큰 배열에서는 성능차이 

In [131]:
x = np.random.standard_normal((1000000,5))

In [132]:
y = 2 * x + 3

In [133]:
C = np.array((x,y), order='C') #행방향
F = np.array((x,y), order='F') #열방향

In [134]:
x = 0.0; y=0.0 # 메모리 해제 (가비지 컬렉션)

In [137]:
C[:2].round(2)

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [138]:
%timeit C.sum()

16.3 ms ± 566 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [139]:
%timeit F.sum()

17.1 ms ± 2.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [140]:
%timeit C.sum(axis=0)

39.5 ms ± 4.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [141]:
%timeit C.sum(axis=1)

99.5 ms ± 22.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [144]:
%timeit F.sum(axis=0)

114 ms ± 4.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [145]:
%timeit F.sum(axis=1)

154 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
